services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tasktracker'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    restart: always

  adminer:
    image: 'adminer:latest'
    restart: always
    ports:
      - '8080:8080'